### ISSUE TITLE
If the sidebar is opened midway the article/page, it scrolls back up then opens the sidebar.

### ISSUE THREAD

**Issue by iAmMrinal0** [punchagan/lanyon#3]
Steps to reproduce:
1. Scroll down a bit on a page.
2. Click the sidebar menu.
3. Page scrolls up and opens the menu.

Expected Result:
The page shouldn't scroll to the top but open the menu at that spot.

**Comment by punchagan** [comment]
Which browser is this on? Unable to reproduce this on Linux with Firefox & Chrome.

**Comment by iAmMrinal0** [comment]
Tested on Linux with:
Chrome version: 50.0.2661.102
Iceweasel version: 38.8.0

**Comment by punchagan** [comment]
How did you install the theme?  This is my own port of the lanyon theme and is not what gets installed using the `nikola` command line tool.  If you installed the theme using `nikola` command line too, please report an issue at https://github.com/getnikola/nikola-themes

**Comment by iAmMrinal0** [comment]
Ah, okay. Sorry for the mistake then. I will report the issue there. Thanks and I will try this one too.
